<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="39986" started-at="2017-12-09T06:06:00Z" finished-at="2017-12-09T06:06:40Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="16022" started-at="2017-12-09T06:06:00Z" finished-at="2017-12-09T06:06:16Z">
      <class name="scripts.TestLogin">
        <test-method status="PASS" signature="openApplication()[pri:0, instance:scripts.TestLogin@2c9f9fb0]" name="openApplication" is-config="true" duration-ms="9824" started-at="2017-12-09T11:36:00Z" finished-at="2017-12-09T11:36:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApplication -->
        <test-method status="FAIL" signature="testLogin()[pri:0, instance:scripts.TestLogin@2c9f9fb0]" name="testLogin" duration-ms="5591" started-at="2017-12-09T11:36:10Z" finished-at="2017-12-09T11:36:15Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [act_TIME] but found [actiTIME - Enter Time-Track]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [act_TIME] but found [actiTIME - Enter Time-Track]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at scripts.TestLogin.testLogin(TestLogin.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method status="PASS" signature="closeApplication()[pri:0, instance:scripts.TestLogin@2c9f9fb0]" name="closeApplication" is-config="true" duration-ms="333" started-at="2017-12-09T11:36:16Z" finished-at="2017-12-09T11:36:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApplication -->
      </class> <!-- scripts.TestLogin -->
    </test> <!-- Test -->
    <test name="Test1" duration-ms="23906" started-at="2017-12-09T06:06:16Z" finished-at="2017-12-09T06:06:40Z">
      <class name="scripts.TestInvalidLogin">
        <test-method status="PASS" signature="openApplication()[pri:0, instance:scripts.TestInvalidLogin@6574b225]" name="openApplication" is-config="true" duration-ms="9056" started-at="2017-12-09T11:36:16Z" finished-at="2017-12-09T11:36:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApplication -->
        <test-method status="PASS" signature="testInvslidLogin()[pri:0, instance:scripts.TestInvalidLogin@6574b225]" name="testInvslidLogin" duration-ms="14511" started-at="2017-12-09T11:36:25Z" finished-at="2017-12-09T11:36:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInvslidLogin -->
        <test-method status="PASS" signature="closeApplication()[pri:0, instance:scripts.TestInvalidLogin@6574b225]" name="closeApplication" is-config="true" duration-ms="337" started-at="2017-12-09T11:36:40Z" finished-at="2017-12-09T11:36:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApplication -->
      </class> <!-- scripts.TestInvalidLogin -->
    </test> <!-- Test1 -->
  </suite> <!-- Suite -->
</testng-results>
